version: 2
 

jobs:
  build:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - restore_cache:
          keys:
            - v0-repo-{{ .Branch }}-{{ .Revision }}
            - v0-repo-{{ .Branch }}
            - v0-repo
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
      - restore_cache:
          keys: 
            - v0-dependencies36-{{ checksum "requirements.txt"}}
            - v0-dependencies36
      - run:
          name: Install
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
          key: v0-dependencies36-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv
      - run: 
          name: Test
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install .
            cd test
            pytest -v --cov satstac.landsat --cov-report term-missing
      - run:
          name: Deploy
          command: |
            if [[ "$CIRCLE_BRANCH" == 'master' ]]; then
              # tag and push to GitHub
              mkdir -p ~/.ssh
              ssh-keyscan github.com >> ~/.ssh/known_hosts              
              VERSION=`awk -F\' '{print $2,$4}' satstac/version.py`
              git tag $VERSION
              git push origin $VERSION
              # deploy Lambda
              sudo pip install awscli
              pip install . -t lambda/
              cd lambda/; zip -ru ../lambda-deploy.zip ./; cd ..
              aws lambda --region us-west-2 update-function-code --function-name sat-stac-landsat --zip-file fileb://lambda-deploy.zip
            fi
