version: 2
 

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
            - v1-repo-{{ .Branch }}
            - v1-repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
      - restore_cache:
          keys: 
            - v1-dependencies36-{{ checksum "requirements.txt"}}
            - v1-dependencies36
      - run: 
          name: Test
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pwd
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install .
            cd test
            pytest -v --cov satstac.landsat --cov-report term-missing
      - save_cache:
          key: v1-dependencies36-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv
      - run:
          name: Deploy
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              pip install awscli
              pip install . -t lambda/
              cd lambda/; zip -ru ../lambda-deploy.zip ./; cd ..
              aws lambda --region us-east-1 update-function-code --function-name sat-stac-landsat --zip-file fileb://lambda-deploy.zip
            fi
